sudo: required
services:
  - docker

before_install:
  - docker build -t marcovgurrola/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true marcovgurrola/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react-001"
  env: "Docker-react-001-env"
  bucket_name: "elasticbeanstalk-eu-central-1-754599169012"
  bucket_path: "docker-react-001"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"